name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: build-app
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun run lint
        continue-on-error: true
      - name: Test
        run: bun run test
      - name: Build app
        run: bun run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          commit_options: '--no-verify --signoff'
